# Generated by Django 3.2.9 on 2021-11-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20211107_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
